const quizData = [
  { english: "purpose", japanese: "そんなことをするのは何が <strong>目的</strong> ですか。", sentence: "What's your (p ) doing that!" },
  { english: "tied", japanese: "彼女は気分転換に後ろで髪 <strong>を結った</strong>。", sentence: "She (t ) her hair back for a change." },
  { english: "hung", japanese: "彼女は壁に新しい絵 <strong>を掛けた</strong>。", sentence: "She (h ) a new picture on the wall." },
  { english: "fly", japanese: "列車に乗るよりも <strong>飛行機で行く</strong> ほうが速い。", sentence: "It is faster to (f ) than take the train." },
  { english: "musical", japanese: "彼はすばらしい <strong>音楽の</strong> 才能を持っている。", sentence: "He has great (m ) talent." },
  { english: "enemies", japanese: "ここには <strong>敵</strong> がたくさんいる。", sentence: "I have a lot of (e ) here." },
  { english: "runs", japanese: "スミスさんは小さな出版社 <strong>を経営している</strong>。", sentence: "Mr. Smith (r ) a small publishing company." },
  { english: "sound", japanese: "<strong>物音</strong> 1つ聞こえなかった。", sentence: "Not a (s ) was heard." },
  { english: "Sounds", japanese: "おもしろ <strong>そうだね</strong>。", sentence: "(S ) like fun." },
  { english: "sound", japanese: "私の息子は自分の将来に関して <strong>しっかりした</strong> 考えを持っている。", sentence: "My son has (s ) ideas about his future." },
  { english: "warning", japanese: "私たちはおしゃべりをしすぎて先生から <strong>注意</strong> を受けた。", sentence: "We received a (w ) from the teacher for talking too much." },
  { english: "pay attention to", japanese: "車を運転するときには他の運転者 <strong>に注意を払う</strong> 必要がある。", sentence: "You need to (p ) other drivers when driving a car." },
  { english: "care", japanese: "彼らが私について何と言っても <strong>気にし</strong> ない。", sentence: "I don't (c ) what they say about me." },
  { english: "took care of", japanese: "ジムは昨日子供の <strong>世話をした</strong>。", sentence: "Jim (t ) his child yesterday." },
  { english: "careful", japanese: "彼は健康にとても <strong>注意している</strong>。", sentence: "He is very (c ) about his health." },
  { english: "carefully", japanese: "箱からコンピューターを <strong>注意深く</strong> 取り出しなさい。", sentence: "Take the computer out of the box (c )." },
  { english: "caution", japanese: "熱い飲み物を注ぐときは <strong>用心しなさい</strong>。", sentence: "Use (c ) when pouring a hot drink." },
  { english: "angel", japanese: "私はよく <strong>天使</strong> の夢を見る。", sentence: "I often dream of an (a )." },
  { english: "fun", japanese: "あなたと一緒に歌うのは <strong>楽しい</strong>。", sentence: "It's (f ) to sing with you." },
  { english: "shape", japanese: "イタリアは形が長靴に似ている。", sentence: "Italy is like a boot in (s )." },
  { english: "form", japanese: "地球の <strong>形</strong> はほぼ球形だ。", sentence: "The (f ) of the earth is nearly round." },
  { english: "animals", japanese: "人間が <strong>動物</strong> を食べることは容認できると思いますか。", sentence: "Do you think it is acceptable for humans to eat (a )?" },
  { english: "remember", japanese: "私は以前彼女に会ったことを <strong>覚えている</strong>。", sentence: "I (r ) seeing her before." },
  { english: "Remember", japanese: "<strong>忘れずに</strong> この手紙を出してね。", sentence: "(R ) to mail this letter." },
  { english: "memorized", japanese: "私は試験のために語いリストを <strong>覚えた</strong>。", sentence: "I (m ) the vocabulary list for the test." },
  { english: "memories", japanese: "この写真を見るといつも思い出が <strong>よみがえる</strong>。", sentence: "Looking at this photo always brings back (m )." },
  { english: "reminded", japanese: "その歌は私に子供の頃のことを <strong>思い出させた</strong>。", sentence: "The song (r ) me of my childhood." },
  { english: "forget", japanese: "<strong>忘れずに</strong> 手紙を書いてね。", sentence: "Don't (f ) to write." },
  { english: "events", japanese: "秋には行事がたくさんある。", sentence: "We have many (e ) in the fall." },
  { english: "Lightning", japanese: "<strong>雷</strong> が時計塔を直撃し、大きな被害が出た。", sentence: "(L ) struck the clock tower and caused a lot of damage." },
  { english: "electricity", japanese: "昨日は <strong>電気</strong> が消えていた。", sentence: "The (e ) was out yesterday." },
  { english: "history", japanese: "ここは <strong>歴史</strong> 上有名な場所だ。", sentence: "This is a place which is famous in (h )." },
  { english: "continued", japanese: "物価は上昇し <strong>続けた</strong>。", sentence: "Prices (c ) rising." },
  { english: "continued", japanese: "夕食後も私は読書し <strong>続けた</strong>。", sentence: "I (c ) to read after dinner." }
];
