const quizData = [
  { english: "probably", japanese: "彼は <strong>おそらく</strong> 試験に合格するだろう。", sentence: "He will ( ) pass the examination." },
  { english: "maybe", japanese: "<strong>おそらく</strong> すぐに彼は来るだろう。", sentence: "( ) he will come soon." },
  { english: "intentionally", japanese: "あなたは <strong>意図的に</strong> 私たちにうそをつきましたね。", sentence: "You have ( ) lied to us." },
  { english: "intend", japanese: "私たちはこの不公平な制度を終わらせる <strong>つもりだ</strong>。", sentence: "We ( ) to end this unfair system." },
  { english: "deliberately", japanese: "A国は <strong>故意に</strong> B国を攻撃している。", sentence: "Country A has ( ) attacked Country B." },
  { english: "almost", japanese: "<strong>ほとんど</strong> すべての葉が散ってしまった。", sentence: "( ) all the leaves have fallen." },
  { english: "bath", japanese: "私はふつうシャワーよりも <strong>ふろ</strong> に入る。", sentence: "I usually take a ( ) rather than a shower." },
  { english: "use", japanese: "あなたはこの新しい情報をどのように <strong>使います</strong> か。", sentence: "How will you ( ) this new information?" },
  { english: "borrow", japanese: "今度の日曜日に君の自転車を <strong>借りて</strong> いいかな?", sentence: "Can I ( ) your bicycle next Sunday?" },
  { english: "lend", japanese: "君の車を <strong>貸して</strong> ください。", sentence: "Please ( ) me your car." },
  { english: "rented", japanese: "私は駅の近くにアパートを <strong>借りた</strong>。", sentence: "I ( ) an apartment near the station." },
  { english: "owe", japanese: "私は昨夜からあなたに20ドル <strong>借りている</strong>。", sentence: "I ( ) you $20 from last night." },
  { english: "debt", japanese: "彼は自分の <strong>借金</strong> を清算した。", sentence: "He cleared his ( )." },
  { english: "marriage", japanese: "彼らは幸せな <strong>結婚生活</strong> を送っています。", sentence: "They have a happy ( )." },
  { english: "ends", japanese: "彼らは同じ <strong>目的</strong> を達成しようとしている。", sentence: "They are trying to achieve the same ( )." },
  { english: "tails", japanese: "多くの動物はバランスをとるのに <strong>しっぽ</strong> を使う。", sentence: "Many animals use their ( ) for balance." },
  { english: "retire", japanese: "私たちの担任の先生は来年 <strong>退職します</strong>。", sentence: "Our homeroom teacher will ( ) next year." },
  { english: "quit", japanese: "もし大金を手に入れたら、仕事を <strong>やめる</strong> だろう。", sentence: "If I won a lot of money, I would ( ) my job." },
  { english: "graduate", japanese: "卒業したあとは何をする <strong>卒業する</strong> つもりですか。", sentence: "What are your plans after you ( )?" },
  { english: "ceased", japanese: "少しすると地震は <strong>収まった</strong>。", sentence: "The earthquake ( ) after a short while." },
  { english: "chance", japanese: "彼女が成功する <strong>見込み</strong> はありますか。", sentence: "Is there any ( ) of her success?" },
  { english: "sure", japanese: "あなたの考えが最善のものだと <strong>確信していますか</strong>。", sentence: "Are you ( ) that your idea is the best one?" },
  { english: "stories", japanese: "両親はしばしば寝る時に子供たちに <strong>お話</strong> をする。", sentence: "Parents often tell their children ( ) at bedtime." },
  { english: "legend", japanese: "この本にある <strong>伝説</strong> を知っていますか。", sentence: "Do you know the ( ) in this book?" },
  { english: "war", japanese: "その2つの国は何十年も <strong>戦争</strong> 中である。", sentence: "The two countries have been at ( ) for decades." },
  { english: "light", japanese: "<strong>軽い</strong> 朝食をとった。", sentence: "I had a ( ) breakfast." },
  { english: "lighter", japanese: "彼は彼女に会って気分が <strong>より明るく</strong> なった。", sentence: "He felt ( ) at heart when he saw her." },
  { english: "shining", japanese: "太陽が明るく <strong>輝いている</strong>。", sentence: "The sun is ( ) brightly." },
  { english: "dark", japanese: "冬は何時に <strong>暗く</strong> になりますか。", sentence: "What time does it get ( ) in winter?" },
  { english: "army", japanese: "父は30年間 <strong>軍隊</strong> にいました。", sentence: "My father was in the ( ) for 30 years." },
  { english: "military", japanese: "私は <strong>軍隊</strong> に費やすお金を削減すべきだと信じています。", sentence: "I believe we should reduce the money we spend on the ( )." },
  { english: "weapons", japanese: "世界は核 <strong>兵器</strong> を排除するために努力しなければならない。", sentence: "The world should work hard to eliminate nuclear ( )." },
  { english: "sign", japanese: "黒い雲は雨の <strong>前触れ</strong> だ。", sentence: "Black clouds are a ( ) of rain." },
  { english: "mark", japanese: "意味のわからない語に <strong>印をつけなさい</strong>。", sentence: "( ) the words you don't understand." },
  { english: "heaven", japanese: "まるで <strong>天国</strong> にいるようでした。", sentence: "It was like I was in ( )." },
  { english: "wood", japanese: "私の机は <strong>木</strong> でできている。", sentence: "My desk is made of ( )." },
  { english: "covered", japanese: "地面は雪で <strong>覆われている</strong>。", sentence: "The land is ( ) with snow." },
  { english: "hide", japanese: "人はしばしば本心を <strong>隠す</strong>。", sentence: "People often ( ) their true feelings." },
  { english: "silk", japanese: "彼女は <strong>絹</strong> の服を着ている。", sentence: "She is dressed in ( )." },
  { english: "later", japanese: "私は金曜と土曜の夜はたいてい、いつもより <strong>遅く</strong> まで起きている。", sentence: "I usually stay up ( ) on Friday and Saturday nights." },
  { english: "learned", japanese: "この授業では何を <strong>学んでいますか</strong>。", sentence: "What have you ( ) in this class?" },
  { english: "master", japanese: "彼女はその言語を <strong>習得する</strong> のに2年かかった。", sentence: "It took her two years to ( ) the language." }
];