const quizData = [
  { english: "probably", japanese: "彼は <strong>おそらく</strong> 試験に合格するだろう。" },
  { english: "maybe", japanese: "<strong>おそらく</strong> すぐに彼は来るだろう。" },
  { english: "intentionally", japanese: "あなたは <strong>意図的に</strong> 私たちにうそをつきましたね。" },
  { english: "intend", japanese: "私たちはこの不公平な制度を終わらせる <strong>つもりだ</strong>。" },
  { english: "deliberately", japanese: "A国は <strong>故意に</strong> B国を攻撃している。" },
  { english: "almost", japanese: "<strong>ほとんど</strong> すべての葉が散ってしまった。" },
  { english: "bath", japanese: "私はふつうシャワーよりも <strong>ふろ</strong> に入る。" },
  { english: "use", japanese: "あなたはこの新しい情報をどのように <strong>使います</strong> か。" },
  { english: "borrow", japanese: "今度の日曜日に君の自転車を <strong>借りて</strong> いいかな?" },
  { english: "lend", japanese: "君の車を <strong>貸して</strong> ください。" },
  { english: "rented", japanese: "私は駅の近くにアパートを <strong>借りた</strong>。" },
  { english: "owe", japanese: "私は昨夜からあなたに20ドル <strong>借りている</strong>。" },
  { english: "debt", japanese: "彼は自分の <strong>借金</strong> を清算した。" },
  { english: "marriage", japanese: "彼らは幸せな <strong>結婚生活</strong> を送っています。" },
  { english: "ends", japanese: "彼らは同じ <strong>目的</strong> を達成しようとしている。" },
  { english: "tails", japanese: "多くの動物はバランスをとるのに <strong>しっぽ</strong> を使う。" },
  { english: "retire", japanese: "私たちの担任の先生は来年 <strong>退職します</strong>。" },
  { english: "quit", japanese: "もし大金を手に入れたら、仕事を <strong>やめる</strong> だろう。" },
  { english: "graduate", japanese: "卒業したあとは何をする <strong>卒業する</strong> つもりですか。" },
  { english: "ceased", japanese: "少しすると地震は <strong>収まった</strong>。" },
  { english: "chance", japanese: "彼女が成功する <strong>見込み</strong> はありますか。" },
  { english: "sure", japanese: "あなたの考えが最善のものだと <strong>確信していますか</strong>。" },
  { english: "stories", japanese: "両親はしばしば寝る時に子供たちに <strong>お話</strong> をする。" },
  { english: "legend", japanese: "この本にある <strong>伝説</strong> を知っていますか。" },
  { english: "war", japanese: "その2つの国は何十年も <strong>戦争</strong> 中である。" },
  { english: "light", japanese: "<strong>軽い</strong> 朝食をとった。" },
  { english: "lighter", japanese: "彼は彼女に会って気分が <strong>より明るく</strong> なった。" },
  { english: "shining", japanese: "太陽が明るく <strong>輝いている</strong>。" },
  { english: "dark", japanese: "冬は何時に <strong>暗く</strong> なりますか。" },
  { english: "army", japanese: "父は30年間 <strong>軍隊</strong> にいました。" },
  { english: "military", japanese: "私は <strong>軍隊</strong> に費やすお金を削減すべきだと信じています。" },
  { english: "weapons", japanese: "世界は核 <strong>兵器</strong> を排除するために努力しなければならない。" },
  { english: "sign", japanese: "黒い雲は雨の <strong>前触れ</strong> だ。" },
  { english: "mark", japanese: "意味のわからない語に <strong>印をつけなさい</strong>。" },
  { english: "heaven", japanese: "まるで <strong>天国</strong> にいるようでした。" },
  { english: "wood", japanese: "私の机は <strong>木</strong> でできている。" },
  { english: "covered", japanese: "地面は雪で <strong>覆われている</strong>。" },
  { english: "hide", japanese: "人はしばしば本心を <strong>隠す</strong>。" },
  { english: "silk", japanese: "彼女は <strong>絹</strong> の服を着ている。" },
  { english: "later", japanese: "私は金曜と土曜の夜はたいてい、いつもより <strong>遅く</strong> まで起きている。" },
  { english: "learned", japanese: "この授業では何を <strong>学んでいますか</strong>。" },
  { english: "master", japanese: "彼女はその言語を <strong>習得する</strong> のに2年かかった。" }
];